### ISSUE TITLE
There's no way to remove comment block without editing JSON settings

### ISSUE THREAD

**Issue by m-heyda** [elpassion/buildel#65]
![image](https://github.com/user-attachments/assets/4d832d0c-90be-4612-8808-e0d88337ccf2)

**Comment by kielbasa-elp** [comment]
@m-heyda Right click on block should open ContextMenu with "Duplicate" and "Delete" options

**Comment by m-heyda** [comment]
Ohh, got ya! Didn't thought about right clicking, In just noticed it because it's the only element which is different and have no icons on it. so might be a little bit confusing 
![image](https://github.com/user-attachments/assets/21eb8411-b4c6-4f76-8743-bfac46cc8a7f)
