### ISSUE TITLE
Key Management QoL

### ISSUE THREAD

**Issue by m-heyda** [elpassion/buildel#69]
Due to the fact that we have “predefined” LLMs and tools, it would be possible to facilitate key management and automatic selection in the Chat block. Currently when you add a chat block by selecting the GPT model you have to choose which key to use, this could be automated. For example when adding a secret in secret page we could add something like "tags" or "categories" so basically you add multiple openAI keys with OpenAI tag and even set "default". So it will be easier to manage those keys filter them etc. And that not everything.

Since we got defaults we could preselect them with default in KEY block field when selected specific LLM. It will make it less painful to configure everytime we add block. (Also we could use localStorge to save field values in text input blocks, so when we switch screen it persist, but that's completely different issue).

Also it could look more "polished" with simple QoL like adding a toast at the top of flow saying "you haven't configured any LLM keys etc" and link to settings for example. Make it very simple, and show it only when there's NO KEY at all, no need to vlaidate etc

**Comment by BartekSniezek** [comment]
In terms of defaults it would be also nice to have default url for each `Model API type`. Right now I need to manually serach for correct api url and replace it

**Comment by michalwarda** [comment]
We've added an idea of "default keys". Now when creating / editing a secret you can check if a secret is a default. If you do so, when creating a new block the secret is automatically chosen.

Check the video to see it.
[Screencast from 2024-09-05 16-04-28.webm](https://github.com/user-attachments/assets/55e9547d-620e-4746-87e8-067a56faf19a)

**Comment by michalwarda** [comment]
@BartekSniezek you can click the highlighted icon to regenerate the default after change: 
![image](https://github.com/user-attachments/assets/faacdb73-b9e5-42e0-a8d4-c575c3cf042c)
